### ISSUE TITLE
Crash on second launch

### ISSUE THREAD

**Issue by thejobbitt** [TheAntTeam/TheAntFarm#13]
**Describe the bug**
Ant Farm crashes on second launch if no connection is made to an Ant.

```
(env) PS C:\TheAntFarm> python .\the_ant_farm.py
Windows Env
Traceback (most recent call last):
  File "C:\TheAntFarm\the_ant_farm.py", line 92, in <module>
    window = MainWindow()
  File "C:\TheAntFarm\the_ant_farm.py", line 45, in __init__
    self.settings.read_all_settings()  # TODO: manage exceptions with a try except
  File "C:\TheAntFarm\settings_manager\settings_manager.py", line 23, in read_all_settings
    self.app_settings.read_all_app_settings()
  File "C:\TheAntFarm\settings_manager\settings_app.py", line 91, in read_all_app_settings
    self.last_serial_baud = app_general.getint("last_serial_baud", self.LAST_SERIAL_BAUD_DEFAULT)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\configparser.py", line 1307, in get
    return _impl(self._name, option, raw=raw, vars=vars,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\configparser.py", line 819, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\configparser.py", line 809, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\configparser.py", line 804, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: ''
```

**Desktop (please complete the following information):**
 - OS: Windows 10 / 11
 - VS code with python environment

**Solution**
In app_config.ini
line 41
```
last_serial_baud =
```
is set to null

Adding a try to:
setting_app.py
line 91
From:
```
self.last_serial_baud = app_general.getint("last_serial_baud", self.LAST_SERIAL_BAUD_DEFAULT)
```

To:
```
try:
self.last_serial_baud = app_general.getint("last_serial_baud", self.LAST_SERIAL_BAUD_DEFAULT)
except:
self.last_serial_baud = self.LAST_SERIAL_BAUD_DEFAULT
```
Fixes the issue.

**Comment by TheAntTeam** [comment]
Hi, 
thanks for the report and the issue solution, I will adopt it (or merge it from you PR).
In general this could happen to any field, so we will be thinking to how to make this part more robust.
